### ISSUE TITLE
Unknown table engine Hive

### ISSUE THREAD

**Issue by nashlibby** [ClickHouse/homebrew-clickhouse#55]
Received exception from server (version 22.7.2):
Code: 56. DB::Exception: Received from localhost:9000. DB::Exception: Unknown table engine Hive. Maybe you meant: ['File']. (UNKNOWN_STORAGE)

**Comment by alexey-milovidov** [comment]
Check the latest release as follows:
```
curl https://clickhouse.com/ | sh
```

**Comment by rschu1ze** [comment]
The repository was [deprecated](https://github.com/ClickHouse/homebrew-clickhouse/pull/71) in favor of a [community-owned ClickHouse formula](https://formulae.brew.sh/cask/clickhouse).
