### ISSUE TITLE
Provide a more recent clickhouse versions

### ISSUE THREAD

**Issue by develar** [ClickHouse/homebrew-clickhouse#56]
Is it possible to provide versions with a lower time gap? Currently, the latest official ClickHouse version is `22.10`, but here 4-months old `22.7`.

**Comment by alexey-milovidov** [comment]
@develar You can download the latest ClickHouse release for Mac as follows:
```
curl https://clickhouse.com/ | sh
```

**Comment by rschu1ze** [comment]
v22.8 is WIP: https://github.com/ClickHouse/homebrew-clickhouse/pull/59. I'll add more recent versions afterwards.
