### ISSUE TITLE
CMake error installing clickhouse@23.5 from brew

### ISSUE THREAD

**Issue by lordvidex** [ClickHouse/homebrew-clickhouse#65]
## System Specs:
Brand: MacOS Intel 2020
OS: Ventura 13.4.1

## Logs:
Installing clickhouse@23.5 from clickhouse/clickhouse
==> cmake -S . -B ./build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=/usr/local/opt
Last 15 lines from /Users/lordvidex/Library/Logs/Homebrew/clickhouse@23.5/01.cmake:
CMake Error at contrib/cctz-cmake/CMakeLists.txt:35 (file):
  file STRINGS file
  "/tmp/clickhouseA23.5-20230712-30051-9qxvfu/contrib/cctz/testdata/version"
  cannot be read.

-- Packaging with tzdata version:
bash: line 0: cd: /tmp/clickhouseA23.5-20230712-30051-9qxvfu/contrib/cctz/testdata/zoneinfo: No such file or directory
CMake Error at cmake/embed_binary.cmake:33 (message):
  The list of binary resources to embed may not be empty
Call Stack (most recent call first):
  contrib/cctz-cmake/CMakeLists.txt:55 (clickhouse_embed_binaries)

-- Configuring incomplete, errors occurred!

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/clickhouse/homebrew-clickhouse/issues

---
**NB:** cask version clickhouse@22.7 works though.

**Comment by rschu1ze** [comment]
The repository was [deprecated](https://github.com/ClickHouse/homebrew-clickhouse/pull/71) in favor of a [community-owned ClickHouse formula](https://formulae.brew.sh/cask/clickhouse).
