### ISSUE TITLE
Missing clickhouse-server/config.xml file

### ISSUE THREAD

**Issue by hooch** [ClickHouse/homebrew-clickhouse#66]
Followed the docs and installed Clickhouse using `brew install clickhouse/clickhouse/clickhouse`

Starting Clickhouse by running `clickhouse server` works, but `brew services start clickhouse` silently fails to start.

The following error appears in the stderr.log:
```
Processing configuration file '/opt/homebrew/etc/clickhouse-server/config.xml'.
Code: 107. DB::Exception: Configuration file /opt/homebrew/etc/clickhouse-server/config.xml doesn't exist. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):
<Empty trace>
 (version 23.5.3.1)
```

My system is Mac OS 13.4.1 on an M1 Max

**Comment by ThomAub** [comment]
Currently solving this by using [default config](https://raw.githubusercontent.com/ClickHouse/ClickHouse/7ac5c421ad66ef6812d05f776b220a810d5e357e/programs/server/config.xml)
```
curl -o $(brew --prefix)/etc/clickhouse-server/config.xml https://raw.githubusercontent.com/ClickHouse/ClickHouse/7ac5c421ad66ef6812d05f776b220a810d5e357e/programs/server/config.xml
```

**Comment by BrickYo** [comment]
users.xml will be introduced in the default configuration file, remember to be in the same directory

curl -o $(brew --prefix)/etc/clickhouse-server/users.xml https://raw.githubusercontent.com/ClickHouse/ClickHouse/master/programs/server/users.xml

**Comment by alex-dixon** [comment]
It's failing on install for me... :(

```
VERSION=v23.8.2.7-lts
curl -o $(brew --prefix)/etc/clickhouse-server/config.xml https://raw.githubusercontent.com/ClickHouse/ClickHouse/$VERSION/programs/server/config.xml

curl -o $(brew --prefix)/etc/clickhouse-server/users.xml https://raw.githubusercontent.com/ClickHouse/ClickHouse/$VERSION/programs/server/users.xml
```

**Comment by rschu1ze** [comment]
The repository was [deprecated](https://github.com/ClickHouse/homebrew-clickhouse/pull/71) in favor of a [community-owned ClickHouse formula](https://formulae.brew.sh/cask/clickhouse).
