### ISSUE TITLE
CMake error installing clickhouse@23.5 from brew

### ISSUE THREAD

**Issue by mdsohelmia** [ClickHouse/homebrew-clickhouse#68]
==> Installing clickhouse@23.5 from clickhouse/clickhouse
==> cmake -S . -B ./build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/
Last 15 lines from /Users/sohelmia/Library/Logs/Homebrew/clickhouse@23.5/01.cmake:
-- Obfuscator mode: ON
-- ODBC bridge mode: OFF
-- Library bridge mode: ON
-- ClickHouse install: ON
-- ClickHouse git-import: ON
-- ClickHouse keeper mode: ON
-- ClickHouse keeper-converter mode: ON
-- ClickHouse keeper-client mode: ON
-- Clickhouse disks mode: ON
-- ClickHouse su: ON
-- bash_completion will be written to /usr/local/Cellar/clickhouse@23.5/23.5.3.24/share/bash-completion/completions
-- Target check already exists
-- /tmp/clickhouseA23.5-20230810-92308-17kxemq/utils: Have 8192 megabytes of memory.
        Limiting concurrent linkers jobs to 2 and compiler jobs to OFF (system has 8 logical cores)
-- Configuring incomplete, errors occurred!

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/clickhouse/homebrew-clickhouse/issues

**Comment by rschu1ze** [comment]
The repository was [deprecated](https://github.com/ClickHouse/homebrew-clickhouse/pull/71) in favor of a [community-owned ClickHouse formula](https://formulae.brew.sh/cask/clickhouse).
